Repository CharVstack/CharV-OAS, pull requests merged in 2022-11, with the labels that each got.

#75 CVS-151 開発ルールの整備
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
Labels: documentation

#76 CVS-152 libとbackendの統合
  .github/workflows/generate_backend.yaml
  .github/workflows/generate_lib.yaml
  gin/models.config.yaml
Labels: enhancement

#81 fix generating package name
  gin/models.config.yaml
Labels: bug

#82 コードジェネレータのコメントを追加
  gin/repackage.awk
Labels: bug

#77 CVS-157 リリースノートの設定ファイルの作成
  .github/release.yml
Labels: documentation

#83 CVS-159 VMの電源状態の変更
  src/v1.json
Labels: enhancement

#84 CVS-160 スキーマ定義のリファクタリング
  src/v1.json
Labels: refactoring

#85 CVS-160 `used_percent` プロパティを `percent` に修正
  src/v1.json
Labels: refactoring

#86 CVS-167 request body を Paths の schema に直接記述
  src/v1.json
Labels: bug

#87 CVS-173 `memory`, `cpu` プロパティの型に `uint64` を指定
  src/v1.json
Labels: bug

#88 CVS-173 Vm models の `memory`, `cpu` プロパティの型に `uint64` を指定
  src/v1.json
Labels: bug

#89 CVS-173 `cpu` プロパティの型を int に修正
  src/v1.json
Labels: bug

#90 CVS-176 openapi2aspidaをforkに切り替え
  package.json
  yarn.lock
Labels: enhancement

#91 CVS-180 openapi2aspidaを上流に戻す
  .github/workflows/generate_backend.yaml
  .github/workflows/generate_frontend.yaml
  package.json
  yarn.lock
Labels: enhancement
