Repository CharVstack/CharV-OAS, pull requests merged in 2022-12, with the labels that each got.

#96 CVS-207 VM電源操作のスキーマ見直し
  src/v1.json
Labels: enhancement

#97 CVS-207 スキーマ内のenumをmodelsに切り出し
  src/v1.json
Labels: bug

#99 CVS-207 CIでベースブランチを参照させる
  .github/workflows/generate_backend.yaml
  .github/workflows/generate_frontend.yaml
Labels: bug

#100 CVS-214 リリースノートに載せる authors から renovate を除外
  .github/release.yml
Labels: enhancement

#98 CVS-209 github actionsの記法を変更
  .github/workflows/build_redoc.yaml
  .github/workflows/generate_backend.yaml
  .github/workflows/generate_frontend.yaml
  .github/workflows/test.yaml
Labels: refactoring

#101 CVS-219 VM削除のエンドポイントを作成
  src/v1.json
Labels: enhancement

#103 CVS-219 intをuint64に戻す
  src/v1.json
Labels: bug

#104 CVS-219 エンドポイントにタグを追加
  src/v1.json
Labels: enhancement

#102 CVS-209 frontend内でyarnのキャッシュを使用する
  .github/workflows/generate_frontend.yaml
Labels: bug
