Repository CharVstack/CharV-OAS, pull requests merged in 2023-02, with the labels that each got.

#105 CVS-231 renovateを調整
  renovate.json
Labels: refactoring

#109 CVS-261 Renovate の構文修正
  renovate.json
Labels: bug

#110 CVS-263 README を作成
  LICENSE
  README.md
Labels: documentation
